# Generated by Django 3.1 on 2020-09-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioner', '0002_customer_house_oderitem_order_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
