# Generated by Django 3.1 on 2020-09-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctioner', '0003_house_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oderitem',
            old_name='product',
            new_name='house',
        ),
    ]
