# Generated by Django 3.0.2 on 2020-06-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_rooms', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('typee', models.CharField(choices=[('Masters', 'Masters'), ('Non Masters', 'Non Masters'), ('I dont Know', 'I dont Know')], max_length=200, null=True)),
                ('short_disc', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, default='try.svg', null=True, upload_to='')),
            ],
        ),
    ]
